apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    namespace: kube-system
    name: pvc-vsphere-csi-test
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
    storageClassName: vsphere-csi-storage-class
